# Generated by Django 3.1 on 2020-09-01 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=30, verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='Abertura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTicket', models.PositiveIntegerField(auto_created=True, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('Aberto', 'ABERTO'), ('Andamento', 'ANDAMENTO'), ('Concluido', 'CONCLUIDO')], default='Aberto', max_length=9)),
                ('descricao', models.TextField(max_length=250)),
                ('descricaoCancelamento', models.TextField(blank=True, max_length=250, null=True)),
                ('descricaoTecnico', models.TextField(blank=True, max_length=250, null=True)),
                ('dataAbertura', models.DateTimeField(auto_now_add=True)),
                ('dataUltimaAlteracao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.setor')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abertura_tecnico', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abertura',
                'verbose_name_plural': 'Aberturas',
            },
        ),
    ]
